# Generated by Django 3.0 on 2019-12-05 21:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tableros', '0002_auto_20191205_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(default=datetime.datetime(2019, 12, 5, 21, 25, 29, 868732, tzinfo=utc))),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableros.Tablero')),
            ],
        ),
    ]
