# Generated by Django 3.0 on 2019-12-05 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_auto_20191205_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='posicion',
            field=models.IntegerField(default=99, max_length=100),
        ),
        migrations.AlterField(
            model_name='lista',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2019, 12, 5, 22, 5, 0, 224117, tzinfo=utc)),
        ),
    ]
