# Generated by Django 3.0 on 2019-12-05 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0005_auto_20191205_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2019, 12, 5, 22, 22, 36, 38339, tzinfo=utc)),
        ),
    ]
