# Generated by Django 3.0 on 2020-03-01 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0017_auto_20191213_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2020, 3, 1, 18, 39, 57, 230392, tzinfo=utc)),
        ),
    ]
