# Generated by Django 3.0 on 2020-03-01 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0019_auto_20200301_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2020, 3, 1, 19, 1, 2, 123492, tzinfo=utc)),
        ),
    ]
