# Generated by Django 3.0 on 2019-12-09 02:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0004_auto_20191209_0228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('fecha_creación', models.DateField(default=datetime.datetime(2019, 12, 9, 2, 28, 9, 992469, tzinfo=utc))),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comdueño', to=settings.AUTH_USER_MODEL)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta', to='cards.Tarjeta')),
            ],
        ),
    ]
