# Generated by Django 3.0 on 2019-12-09 02:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='fecha_creación',
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2019, 12, 9, 2, 32, 17, 186623, tzinfo=utc)),
        ),
    ]
