# Generated by Django 3.0 on 2020-03-01 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0005_auto_20200301_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2020, 3, 1, 18, 49, 25, 447874, tzinfo=utc)),
        ),
    ]
