# Generated by Django 3.0 on 2020-03-01 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0010_auto_20200301_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2020, 3, 1, 22, 2, 16, 864613, tzinfo=utc)),
        ),
    ]
