# Generated by Django 3.0 on 2019-12-05 21:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_de_creacion', models.DateField(default=datetime.datetime(2019, 12, 5, 21, 1, 18, 905816, tzinfo=utc))),
                ('visibilidad', models.CharField(choices=[('V', 'Visible'), ('N', 'No visible')], max_length=1)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueño', to=settings.AUTH_USER_MODEL)),
                ('favorito', models.ManyToManyField(related_name='favorito', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(related_name='miembros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
