# Generated by Django 3.0 on 2019-12-05 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='fecha_de_creacion',
            field=models.DateField(default=datetime.datetime(2019, 12, 5, 21, 25, 29, 867108, tzinfo=utc)),
        ),
    ]
