# Generated by Django 3.0 on 2019-12-05 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0003_auto_20191205_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='fecha_de_creacion',
            field=models.DateField(default=datetime.datetime(2019, 12, 5, 22, 5, 0, 222476, tzinfo=utc)),
        ),
    ]
