# Generated by Django 3.0 on 2019-12-09 01:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0011_auto_20191205_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='fecha_de_creacion',
            field=models.DateField(default=datetime.datetime(2019, 12, 9, 1, 56, 16, 384694, tzinfo=utc)),
        ),
    ]
