# Generated by Django 3.0 on 2020-03-01 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0018_auto_20191213_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='fecha_de_creacion',
            field=models.DateField(default=datetime.datetime(2020, 3, 1, 22, 2, 53, 180490, tzinfo=utc)),
        ),
    ]
