# Generated by Django 3.0 on 2020-03-01 22:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tableros', '0019_auto_20200301_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='dueño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dueño', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='fecha_de_creacion',
            field=models.DateField(default=datetime.datetime(2020, 3, 1, 22, 13, 49, 959688, tzinfo=utc)),
        ),
    ]
